// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Magazynuj.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Magazynuj.Data.Data
{
    public partial class WarehouseManagementContext
    {
        private IWarehouseManagementContextProcedures _procedures;

        public virtual IWarehouseManagementContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new WarehouseManagementContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IWarehouseManagementContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class WarehouseManagementContextProcedures : IWarehouseManagementContextProcedures
    {
        private readonly WarehouseManagementContext _context;

        public WarehouseManagementContextProcedures(WarehouseManagementContext context)
        {
            _context = context;
        }
    }
}
