// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class AdditionalRemuneration
    {
        public AdditionalRemuneration()
        {
            Remuneration = new HashSet<Remuneration>();
        }

        [Column("additionalRemunerationType_id")]
        public int? AdditionalRemunerationTypeId { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("AdditionalRemuneration")]
        public virtual ICollection<Remuneration> Remuneration { get; set; }
    }
}