// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Adres
    {
        public Adres()
        {
            Bank = new HashSet<Bank>();
            Company = new HashSet<Company>();
            Contractor = new HashSet<Contractor>();
            PersonalData = new HashSet<PersonalData>();
            Warehouse = new HashSet<Warehouse>();
        }

        [Required]
        [Column("street")]
        [StringLength(255)]
        [Unicode(false)]
        public string Street { get; set; }
        [Required]
        [Column("city")]
        [StringLength(255)]
        [Unicode(false)]
        public string City { get; set; }
        [Column("houseNumber")]
        public int HouseNumber { get; set; }
        [Required]
        [Column("postalCode")]
        [StringLength(6)]
        [Unicode(false)]
        public string PostalCode { get; set; }
        [Column("country")]
        [StringLength(255)]
        [Unicode(false)]
        public string Country { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("Adres")]
        public virtual ICollection<Bank> Bank { get; set; }
        [InverseProperty("Adres")]
        public virtual ICollection<Company> Company { get; set; }
        [InverseProperty("Adres")]
        public virtual ICollection<Contractor> Contractor { get; set; }
        [InverseProperty("Adres")]
        public virtual ICollection<PersonalData> PersonalData { get; set; }
        [InverseProperty("Adres")]
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}