// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class ClientType
    {
        public ClientType()
        {
            Client = new HashSet<Client>();
            Discount = new HashSet<Discount>();
        }

        [Column("nameCientType")]
        [StringLength(255)]
        [Unicode(false)]
        public string NameCientType { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("ClientType")]
        public virtual ICollection<Client> Client { get; set; }
        [InverseProperty("ClientType")]
        public virtual ICollection<Discount> Discount { get; set; }
    }
}