// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Commodity
    {
        public Commodity()
        {
            WarehouseReceipts = new HashSet<WarehouseReceipts>();
        }

        [Required]
        [Column("code")]
        [StringLength(255)]
        [Unicode(false)]
        public string Code { get; set; }
        [Required]
        [Column("nameCommodity")]
        [StringLength(255)]
        [Unicode(false)]
        public string NameCommodity { get; set; }
        [Required]
        [Column("rateVAT")]
        [StringLength(55)]
        [Unicode(false)]
        public string RateVat { get; set; }
        [Required]
        [Column("jm")]
        [StringLength(55)]
        [Unicode(false)]
        public string Jm { get; set; }
        [Column("priceA", TypeName = "decimal(10, 2)")]
        public decimal PriceA { get; set; }
        [Column("priceB", TypeName = "decimal(10, 2)")]
        public decimal PriceB { get; set; }
        [Column("priceC", TypeName = "decimal(10, 2)")]
        public decimal PriceC { get; set; }
        [Column("priceD", TypeName = "decimal(10, 2)")]
        public decimal PriceD { get; set; }
        [Required]
        [Column("codeEAN")]
        [StringLength(255)]
        [Unicode(false)]
        public string CodeEan { get; set; }
        [Column("bruttoA", TypeName = "decimal(10, 2)")]
        public decimal BruttoA { get; set; }
        [Column("bruttoB", TypeName = "decimal(10, 2)")]
        public decimal BruttoB { get; set; }
        [Column("bruttoC", TypeName = "decimal(10, 2)")]
        public decimal BruttoC { get; set; }
        [Column("bruttoD", TypeName = "decimal(10, 2)")]
        public decimal BruttoD { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("employee_id")]
        public Guid? EmployeeId { get; set; }
        [Column("commodityCategory_id")]
        public Guid? CommodityCategoryId { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }

        [ForeignKey("CommodityCategoryId")]
        [InverseProperty("Commodity")]
        public virtual CommodityCategory CommodityCategory { get; set; }
        [ForeignKey("EmployeeId")]
        [InverseProperty("Commodity")]
        public virtual Employee Employee { get; set; }
        [InverseProperty("Commodity")]
        public virtual ICollection<WarehouseReceipts> WarehouseReceipts { get; set; }
    }
}