// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class CommodityDetails
    {
        [Column("colour")]
        [StringLength(255)]
        [Unicode(false)]
        public string Colour { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("storagePlace_id")]
        public Guid? StoragePlaceId { get; set; }
        [Column("commodityDimentions_id")]
        public Guid? CommodityDimentionsId { get; set; }
        [Column("commodityMark_id")]
        public Guid? CommodityMarkId { get; set; }

        [ForeignKey("CommodityDimentionsId")]
        [InverseProperty("CommodityDetails")]
        public virtual CommodityDimensions CommodityDimentions { get; set; }
        [ForeignKey("CommodityMarkId")]
        [InverseProperty("CommodityDetails")]
        public virtual CommodityMark CommodityMark { get; set; }
        [ForeignKey("StoragePlaceId")]
        [InverseProperty("CommodityDetails")]
        public virtual StoragePlace StoragePlace { get; set; }
    }
}