// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class CommodityDimensions
    {
        public CommodityDimensions()
        {
            CommodityDetails = new HashSet<CommodityDetails>();
        }

        [Column("dimensions")]
        [StringLength(255)]
        [Unicode(false)]
        public string Dimensions { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("CommodityDimentions")]
        public virtual ICollection<CommodityDetails> CommodityDetails { get; set; }
    }
}