// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class CommodityCategory
    {
        public CommodityCategory()
        {
            Commodity = new HashSet<Commodity>();
        }

        [Column("nameCategory")]
        [StringLength(255)]
        [Unicode(false)]
        public string NameCategory { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("CommodityCategory")]
        public virtual ICollection<Commodity> Commodity { get; set; }
    }
}