// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class CompanyDetail
    {
        public CompanyDetail()
        {
            Company = new HashSet<Company>();
        }

        [Column("nip")]
        [StringLength(10)]
        [Unicode(false)]
        public string Nip { get; set; }
        [Column("regon")]
        [StringLength(9)]
        [Unicode(false)]
        public string Regon { get; set; }
        [Column("krs")]
        [StringLength(10)]
        [Unicode(false)]
        public string Krs { get; set; }
        [Column("phoneNumber")]
        [StringLength(12)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Column("email")]
        [StringLength(255)]
        [Unicode(false)]
        public string Email { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("issuerDocument_id")]
        public Guid? IssuerDocumentId { get; set; }

        [InverseProperty("CompanyDetail")]
        public virtual ICollection<Company> Company { get; set; }
    }
}