// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Company
    {
        public Company()
        {
            Invoice = new HashSet<Invoice>();
        }

        [Column("nameCompany")]
        [StringLength(255)]
        [Unicode(false)]
        public string NameCompany { get; set; }
        [Column("description")]
        [StringLength(1)]
        [Unicode(false)]
        public string Description { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("country_id")]
        public Guid? CountryId { get; set; }
        [Column("contractor_id")]
        public Guid? ContractorId { get; set; }
        [Column("bank_id")]
        public Guid? BankId { get; set; }
        [Column("companyDetail_id")]
        public Guid? CompanyDetailId { get; set; }
        [Column("adres_id")]
        public Guid? AdresId { get; set; }

        [ForeignKey("AdresId")]
        [InverseProperty("Company")]
        public virtual Adres Adres { get; set; }
        [ForeignKey("BankId")]
        [InverseProperty("Company")]
        public virtual Bank Bank { get; set; }
        [ForeignKey("CompanyDetailId")]
        [InverseProperty("Company")]
        public virtual CompanyDetail CompanyDetail { get; set; }
        [ForeignKey("ContractorId")]
        [InverseProperty("Company")]
        public virtual Contractor Contractor { get; set; }
        [ForeignKey("CountryId")]
        [InverseProperty("Company")]
        public virtual Country Country { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}