// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class CompanyLocation
    {
        public CompanyLocation()
        {
            Department = new HashSet<Department>();
        }

        [Column("locationName")]
        [StringLength(255)]
        [Unicode(false)]
        public string LocationName { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("officeKey_id")]
        public Guid? OfficeKeyId { get; set; }

        [ForeignKey("OfficeKeyId")]
        [InverseProperty("CompanyLocation")]
        public virtual OfficeKeys OfficeKey { get; set; }
        [InverseProperty("CompanyLocation")]
        public virtual ICollection<Department> Department { get; set; }
    }
}