// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class ContractData
    {
        [Column("signingDate", TypeName = "datetime")]
        public DateTime? SigningDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("supplier_id")]
        public Guid? SupplierId { get; set; }

        [ForeignKey("Id")]
        [InverseProperty("ContractData")]
        public virtual Supplier IdNavigation { get; set; }
    }
}