// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Contractor
    {
        public Contractor()
        {
            Company = new HashSet<Company>();
            Invoice = new HashSet<Invoice>();
        }

        [Required]
        [Column("codeContractor")]
        [StringLength(55)]
        [Unicode(false)]
        public string CodeContractor { get; set; }
        [Required]
        [Column("nameContractor")]
        [StringLength(250)]
        public string NameContractor { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("personalData_id")]
        public Guid? PersonalDataId { get; set; }
        [Column("adres_id")]
        public Guid? AdresId { get; set; }
        [Column("contractorDetail_id")]
        public Guid? ContractorDetailId { get; set; }
        [Column("authorizedPerson_id")]
        public Guid? AuthorizedPersonId { get; set; }
        [Column("isActive")]
        public bool? IsActive { get; set; }

        [ForeignKey("AdresId")]
        [InverseProperty("Contractor")]
        public virtual Adres Adres { get; set; }
        [ForeignKey("ContractorDetailId")]
        [InverseProperty("Contractor")]
        public virtual ContractorDetail ContractorDetail { get; set; }
        [ForeignKey("PersonalDataId")]
        [InverseProperty("Contractor")]
        public virtual PersonalData PersonalData { get; set; }
        [InverseProperty("Contractor")]
        public virtual ICollection<Company> Company { get; set; }
        [InverseProperty("Contractor")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}