// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Country
    {
        public Country()
        {
            Company = new HashSet<Company>();
        }

        [StringLength(255)]
        [Unicode(false)]
        public string CountryName { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("Country")]
        public virtual ICollection<Company> Company { get; set; }
    }
}