// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class DefaultPriceList
    {
        public DefaultPriceList()
        {
            ContractorDetail = new HashSet<ContractorDetail>();
        }

        [Column("nameDefaultPriceList")]
        [StringLength(255)]
        [Unicode(false)]
        public string NameDefaultPriceList { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("DefaultPriceList")]
        public virtual ICollection<ContractorDetail> ContractorDetail { get; set; }

        public override string ToString()
        {
            return NameDefaultPriceList;
        }
    }
}