// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Department
    {
        public Department()
        {
            Employee = new HashSet<Employee>();
        }

        [Column("nameDepartment")]
        [StringLength(255)]
        [Unicode(false)]
        public string NameDepartment { get; set; }
        [Column("numberOfEmployees")]
        public int? NumberOfEmployees { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("companyLocation_id")]
        public Guid? CompanyLocationId { get; set; }

        [ForeignKey("CompanyLocationId")]
        [InverseProperty("Department")]
        public virtual CompanyLocation CompanyLocation { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}