// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class DiscountType
    {
        public DiscountType()
        {
            Discount = new HashSet<Discount>();
        }

        [Column("onlyPoland")]
        public bool? OnlyPoland { get; set; }
        [Column("onlyPLN")]
        public bool? OnlyPln { get; set; }
        [Column("name")]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("DiscountType")]
        public virtual ICollection<Discount> Discount { get; set; }
    }
}