// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Commodity = new HashSet<Commodity>();
            FixedAssets = new HashSet<FixedAssets>();
            ShiftSupervisor = new HashSet<ShiftSupervisor>();
            VacationDays = new HashSet<VacationDays>();
            VacationSchedule = new HashSet<VacationSchedule>();
        }

        [Key]
        public Guid Id { get; set; }
        [Column("warehouse_id")]
        public Guid? WarehouseId { get; set; }
        [Column("workType_id")]
        public Guid? WorkTypeId { get; set; }
        [Column("remuneration_id")]
        public Guid? RemunerationId { get; set; }
        [Column("department_id")]
        public Guid? DepartmentId { get; set; }
        [Column("personalData_id")]
        public Guid? PersonalDataId { get; set; }

        [ForeignKey("DepartmentId")]
        [InverseProperty("Employee")]
        public virtual Department Department { get; set; }
        [ForeignKey("Id")]
        [InverseProperty("Employee")]
        public virtual Warehouse IdNavigation { get; set; }
        [ForeignKey("PersonalDataId")]
        [InverseProperty("Employee")]
        public virtual PersonalData PersonalData { get; set; }
        [ForeignKey("RemunerationId")]
        [InverseProperty("Employee")]
        public virtual Remuneration Remuneration { get; set; }
        [ForeignKey("WorkTypeId")]
        [InverseProperty("Employee")]
        public virtual WorkType WorkType { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<Commodity> Commodity { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<FixedAssets> FixedAssets { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<ShiftSupervisor> ShiftSupervisor { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<VacationDays> VacationDays { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<VacationSchedule> VacationSchedule { get; set; }
    }
}