// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class FixedAssets
    {
        [Column("releaseDate", TypeName = "datetime")]
        public DateTime? ReleaseDate { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("employee_id")]
        public Guid? EmployeeId { get; set; }
        [Column("fixedAssetsType_id")]
        public Guid? FixedAssetsTypeId { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("FixedAssets")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("FixedAssetsTypeId")]
        [InverseProperty("FixedAssets")]
        public virtual FixedAssetsType FixedAssetsType { get; set; }
    }
}