// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Gender
    {
        public Gender()
        {
            Client = new HashSet<Client>();
        }

        [Column("genderName")]
        [StringLength(1)]
        [Unicode(false)]
        public string GenderName { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("Gender")]
        public virtual ICollection<Client> Client { get; set; }
    }
}