// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class InvoiceType
    {
        public InvoiceType()
        {
            Invoice = new HashSet<Invoice>();
        }

        [Column("isElectronic")]
        public byte? IsElectronic { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("InvoiceType")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}