// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Invoice
    {
        public Invoice()
        {
            OrderTab = new HashSet<OrderTab>();
        }

        [Column("number")]
        public int? Number { get; set; }
        [Column("issueDate", TypeName = "datetime")]
        public DateTime? IssueDate { get; set; }
        [Column("nettoValue", TypeName = "decimal(10, 2)")]
        public decimal? NettoValue { get; set; }
        [Column("rateVAT")]
        [StringLength(55)]
        [Unicode(false)]
        public string RateVat { get; set; }
        [Column("bruttoValue", TypeName = "decimal(10, 2)")]
        public decimal? BruttoValue { get; set; }
        [Column("paidValue", TypeName = "decimal(10, 2)")]
        public decimal? PaidValue { get; set; }
        [Column("description")]
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("leftToPay", TypeName = "decimal(10, 2)")]
        public decimal? LeftToPay { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("company_id")]
        public Guid? CompanyId { get; set; }
        [Column("payment_id")]
        public Guid? PaymentId { get; set; }
        [Column("discount_id")]
        public Guid? DiscountId { get; set; }
        [Column("client_id")]
        public Guid? ClientId { get; set; }
        [Column("issuingDocumentPerson_id")]
        public Guid? IssuingDocumentPersonId { get; set; }
        [Column("bank_id")]
        public Guid? BankId { get; set; }
        [Column("contractor_id")]
        public Guid? ContractorId { get; set; }
        [Column("invoiceType_id")]
        public Guid? InvoiceTypeId { get; set; }

        [ForeignKey("BankId")]
        [InverseProperty("Invoice")]
        public virtual Bank Bank { get; set; }
        [ForeignKey("ClientId")]
        [InverseProperty("Invoice")]
        public virtual Client Client { get; set; }
        [ForeignKey("CompanyId")]
        [InverseProperty("Invoice")]
        public virtual Company Company { get; set; }
        [ForeignKey("ContractorId")]
        [InverseProperty("Invoice")]
        public virtual Contractor Contractor { get; set; }
        [ForeignKey("DiscountId")]
        [InverseProperty("Invoice")]
        public virtual Discount Discount { get; set; }
        [ForeignKey("InvoiceTypeId")]
        [InverseProperty("Invoice")]
        public virtual InvoiceType InvoiceType { get; set; }
        [ForeignKey("PaymentId")]
        [InverseProperty("Invoice")]
        public virtual Payment Payment { get; set; }
        [InverseProperty("Invoice")]
        public virtual ICollection<OrderTab> OrderTab { get; set; }
    }
}