// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class LoyaltyCard
    {
        [Column("cardNumber")]
        [StringLength(10)]
        [Unicode(false)]
        public string CardNumber { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("client_id")]
        public Guid? ClientId { get; set; }
    }
}