// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class MaritalStatus
    {
        public MaritalStatus()
        {
            Client = new HashSet<Client>();
        }

        [Column("maritalStatus")]
        [StringLength(30)]
        [Unicode(false)]
        public string MaritalStatus1 { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("MaritalStatus")]
        public virtual ICollection<Client> Client { get; set; }
    }
}