// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class OfficeKeys
    {
        public OfficeKeys()
        {
            CompanyLocation = new HashSet<CompanyLocation>();
        }

        [Column("keyNumber")]
        [StringLength(10)]
        [Unicode(false)]
        public string KeyNumber { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("OfficeKey")]
        public virtual ICollection<CompanyLocation> CompanyLocation { get; set; }
    }
}