// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class OrderType
    {
        public OrderType()
        {
            OrderTab = new HashSet<OrderTab>();
        }

        [Column("name")]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty("OrderType")]
        public virtual ICollection<OrderTab> OrderTab { get; set; }
    }
}