// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class OrderTab
    {
        [Column("deliveryDate", TypeName = "datetime")]
        public DateTime? DeliveryDate { get; set; }
        [Column("placingOrderDate", TypeName = "datetime")]
        public DateTime? PlacingOrderDate { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("OrderType_id")]
        public Guid? OrderTypeId { get; set; }
        [Column("deliveryAdres_id")]
        public Guid? DeliveryAdresId { get; set; }
        [Column("invoice_id")]
        public Guid? InvoiceId { get; set; }

        [ForeignKey("InvoiceId")]
        [InverseProperty("OrderTab")]
        public virtual Invoice Invoice { get; set; }
        [ForeignKey("OrderTypeId")]
        [InverseProperty("OrderTab")]
        public virtual OrderType OrderType { get; set; }
    }
}