// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class PaymentType
    {
        public PaymentType()
        {
            Payment = new HashSet<Payment>();
        }

        [Column("name")]
        [StringLength(25)]
        [Unicode(false)]
        public string Name { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("payrollClient_id")]
        public Guid? PayrollClientId { get; set; }

        [ForeignKey("PayrollClientId")]
        [InverseProperty("PaymentType")]
        public virtual PayrollClient PayrollClient { get; set; }
        [InverseProperty("PaymentType")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}