// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Payment
    {
        public Payment()
        {
            Invoice = new HashSet<Invoice>();
        }

        [Column("paymentDate", TypeName = "datetime")]
        public DateTime? PaymentDate { get; set; }
        [Column("paymentValue", TypeName = "decimal(10, 2)")]
        public decimal? PaymentValue { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("paymentType_id")]
        public Guid? PaymentTypeId { get; set; }

        [ForeignKey("PaymentTypeId")]
        [InverseProperty("Payment")]
        public virtual PaymentType PaymentType { get; set; }
        [InverseProperty("Payment")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}