// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Remuneration
    {
        public Remuneration()
        {
            Employee = new HashSet<Employee>();
        }

        [Column("value", TypeName = "decimal(10, 2)")]
        public decimal? Value { get; set; }
        [Column("date", TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [Column("description")]
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("additionalRemuneration_id")]
        public Guid? AdditionalRemunerationId { get; set; }

        [ForeignKey("AdditionalRemunerationId")]
        [InverseProperty("Remuneration")]
        public virtual AdditionalRemuneration AdditionalRemuneration { get; set; }
        [InverseProperty("Remuneration")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}