// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class ShiftSupervisor
    {
        [Key]
        public Guid Id { get; set; }
        [Column("employee_id")]
        public Guid? EmployeeId { get; set; }
        [Column("shiftType_id")]
        public Guid? ShiftTypeId { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("ShiftSupervisor")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("ShiftTypeId")]
        [InverseProperty("ShiftSupervisor")]
        public virtual ShiftType ShiftType { get; set; }
    }
}