// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class VacationSchedule
    {
        [Column("startDate", TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column("endDate", TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Column("usedDays")]
        public int? UsedDays { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("employee_id")]
        public Guid? EmployeeId { get; set; }
        [Column("vacationType_id")]
        public Guid? VacationTypeId { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("VacationSchedule")]
        public virtual Employee Employee { get; set; }
        [ForeignKey("VacationTypeId")]
        [InverseProperty("VacationSchedule")]
        public virtual VacationType VacationType { get; set; }
    }
}