// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class Warehouse
    {
        public Warehouse()
        {
            StoragePlace = new HashSet<StoragePlace>();
        }

        [Column("name")]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("adres_id")]
        public Guid? AdresId { get; set; }

        [ForeignKey("AdresId")]
        [InverseProperty("Warehouse")]
        public virtual Adres Adres { get; set; }
        [InverseProperty("IdNavigation")]
        public virtual Employee Employee { get; set; }
        [InverseProperty("Warehouse")]
        public virtual ICollection<StoragePlace> StoragePlace { get; set; }
    }
}