// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class WarehouseReceipts
    {
        [Column(TypeName = "datetime")]
        public DateTime? ReceiptDate { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("supplier_id")]
        public Guid? SupplierId { get; set; }
        [Column("commodity_id")]
        public Guid? CommodityId { get; set; }

        [ForeignKey("CommodityId")]
        [InverseProperty("WarehouseReceipts")]
        public virtual Commodity Commodity { get; set; }
        [ForeignKey("Id")]
        [InverseProperty("WarehouseReceipts")]
        public virtual Supplier IdNavigation { get; set; }
    }
}