// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Magazynuj.Data.Models
{
    public partial class WorkType
    {
        public WorkType()
        {
            Employee = new HashSet<Employee>();
        }

        [Column("description")]
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }
        [Key]
        public Guid Id { get; set; }
        [Column("shiftType_id")]
        public Guid? ShiftTypeId { get; set; }

        [InverseProperty("WorkType")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}